Improve rosbuild and roslurdf functions for better error handling and user experience; add checks for file existence in roslurdf

diff --git a/rosrc b/rosrc
--- a/rosrc
+++ b/rosrc
@@ -126,8 +126,25 @@ __rosrc() {
   }
 
   roslurdf() {
-    ros2 launch urdf_tutorial display.launch.py model:=/home/ubuntu/ros2_ws/src/yahboom_rosmaster/yahboom_rosmaster_description/urdf/robots/rosmaster_x3.urdf.xacro
+    # Command requires the absolute path. Check if it throws error
+    if ! ros2 launch urdf_tutorial display.launch.py model:="$1" >/dev/null 2>&1; then
+      # Check if the file exists in the current directory
+      if [ -f "$1" ]; then
+        ros2 launch urdf_tutorial display.launch.py model:=$(pwd)/"$1" >/dev/null 2>&1
+        return
+      fi
+      # Check if the file exists in the workspace
+      if [ -f "$ROS_WS"/src/"$1" ]; then
+        ros2 launch urdf_tutorial display.launch.py model:="$ROS_WS"/src/"$1" >/dev/null 2>&1
+        return
+      fi
+      # If all attempts fail, print an error message
+      echo "🗷 Error: Failed to launch URDF model '$1'. File not found or launch failed."
+      return 1
+    fi
   }
+
+  ############################################################################################
 
   # Source the ROS setup file for the extracted distribution
   if source /opt/ros/${ROS_DISTRO}/setup.bash 2>/dev/null; then
@@ -174,7 +191,7 @@ rosinstall() {
   # Install ROS, RViz, Demos, Tutorials
   sudo apt install --reinstall -y ros-$ROS_DISTRO-desktop
   # Install Gazebo Simulation for your robots
-  sudo apt install --reinstall -y ros-$ROS_DISTRO-ros-gz 
+  sudo apt install --reinstall -y ros-$ROS_DISTRO-ros-gz
   # Install ROS 2 command line tools
   sudo apt install --reinstall -y ros-$ROS_DISTRO-urdf-tutorial
   # Find which python version ROS 2 is using
