Comment out verification steps for ROS 2 installation in CI workflow

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -14,15 +14,16 @@ jobs:
         branch: ${{ github.ref_name }}
       run: |
         wget -O - https://raw.githubusercontent.com/uniquetrij/rosrc/${branch:-main}/ros-installer.sh | sh
-    - name: Verify ROS 2 Installation
-      if: false
-      run: |
-        if [ ! -z $(dpkg -l | grep ros-$(ls /opt/ros/) | wc -l) ]; then
-          echo "Installation successful."
-        else
-          echo "Installation failed."
-          exit 1
-        fi
+  #   - name: Verify ROS 2 Installation
+  #     if: false
+  #     run: |
+  #       if [ ! -z $(dpkg -l | grep ros-$(ls /opt/ros/) | wc -l) ]; then
+  #         echo "Installation successful."
+  #       else
+  #         echo "Installation failed."
+  #         exit 1
+  #       fi
+
   #   - name: Verify Miniconda3 Installation
   #     run: |
   #       if [ ! -z "(conda -V)" ]; then
